### ISSUE TITLE
version is not a function

### ISSUE THREAD

**Issue by bibby** [bySabi/safe-commander.js#1]
It seems you might be missing [this method](https://github.com/tj/commander.js/blob/v2.4.0/index.js#L679) to be able to run your own example.  I might be wrong, but I get..

```
> var program = require('safe-commander');
undefined
> program.version('0.0.0')
TypeError: program.version is not a function
    at repl:1:9
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> program
Command {
  commands: [],
  options: [],
  _execs: {},
  _allowUnknownOption: false,
  _args: [],
  _name: '',
  optsObj: {},
  Command: [Function: Command],
  Option: [Function: Option] }
> 

```

**Comment by bibby** [comment]
`option` and `parse` are also not functions.  Clearly I have misunderstood this module's use.

**Comment by bibby** [comment]
Strange..  I have to do this to make it work,

```
var Command = require('safe-commander').Command;   // safe-commander
var program = new Command();
```

It doesn't make sense to me, because the main export is already a new Command instance.

Ignore my flailing.

**Comment by bySabi** [comment]
@bibbly thanks for report.

Was a early exports, thats why your second version works.

Please update to new release.
